import type { CloseControlCertificationSafetyRuntimeActionAbsenceBoundary } from "@pocket-cto/domain";

const actionBoundaryKeys = [
  "runtimeCodexUsed",
  "deliveryCreated",
  "externalProviderCalled",
  "notificationProviderCalled",
  "providerCredentialCreated",
  "providerJobCreated",
  "outboxSendCreated",
  "emailSent",
  "slackSent",
  "smsSent",
  "webhookCalled",
  "scheduledDeliveryCreated",
  "autoSendConfigured",
  "reportCreated",
  "reportReleased",
  "reportCirculated",
  "approvalCreated",
  "certificationCreated",
  "closeCompleteCreated",
  "signOffCreated",
  "attestationCreated",
  "assuranceCreated",
  "legalOpinionCreated",
  "auditOpinionCreated",
  "missionCreated",
  "monitorRunTriggered",
  "monitorResultCreated",
  "sourceMutationCreated",
  "generatedProseCreated",
  "generatedNotificationProseCreated",
  "accountingWriteCreated",
  "bankWriteCreated",
  "taxFilingCreated",
  "legalAdviceGenerated",
  "policyAdviceGenerated",
  "paymentInstructionCreated",
  "collectionInstructionCreated",
  "customerContactInstructionCreated",
  "autonomousActionCreated",
] as const;

export function hasUnexpectedActionBoundaryValue(
  boundaries: Array<Record<string, unknown>>,
) {
  return boundaries.some((boundary) =>
    actionBoundaryKeys.some((key) => boundary[key] === true),
  );
}

export function buildRuntimeActionBoundary(): CloseControlCertificationSafetyRuntimeActionAbsenceBoundary {
  return {
    runtimeCodexUsed: false,
    deliveryCreated: false,
    externalProviderCalled: false,
    notificationProviderCalled: false,
    providerCredentialCreated: false,
    providerJobCreated: false,
    outboxSendCreated: false,
    emailSent: false,
    slackSent: false,
    smsSent: false,
    webhookCalled: false,
    scheduledDeliveryCreated: false,
    autoSendConfigured: false,
    reportCreated: false,
    reportReleased: false,
    reportCirculated: false,
    approvalCreated: false,
    certificationCreated: false,
    closeCompleteCreated: false,
    signOffCreated: false,
    attestationCreated: false,
    assuranceCreated: false,
    legalOpinionCreated: false,
    auditOpinionCreated: false,
    missionCreated: false,
    monitorRunTriggered: false,
    monitorResultCreated: false,
    sourceMutationCreated: false,
    generatedProseCreated: false,
    generatedNotificationProseCreated: false,
    accountingWriteCreated: false,
    bankWriteCreated: false,
    taxFilingCreated: false,
    legalAdviceGenerated: false,
    policyAdviceGenerated: false,
    paymentInstructionCreated: false,
    collectionInstructionCreated: false,
    customerContactInstructionCreated: false,
    autonomousActionCreated: false,
    summary:
      "F6T certification-safety generation is deterministic, read-only, internal, and no certification occurred.",
    replayImplication:
      "The first F6T certification-safety result is derived from current stored/read posture and is not persisted as a mission replay event.",
  };
}
